version: dev.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - main
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2022
platform:
- x64
- Win32
configuration:
- Release
- Debug
- ASAN-Release
- ASAN-Debug
shallow_clone: false
cache:
  - C:\RLibrary
  - C:\Program Files (x86)\Pandoc\
install:
  - ps: >-
      if (-Not (Test-Path "C:\Program Files (x86)\Pandoc\")) {
        cinst pandoc
      }
  - ps: $env:Path += ";C:\Program Files (x86)\Pandoc\"
  - pandoc -v
  - git submodule update --init --recursive
build:
  project: Dn-FamiTracker.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: for /f "tokens=*" %%a in ('git describe --tags') do (set commithash=%%a)
- cmd: call release.bat %configuration% %platform% %commithash%_%APPVEYOR_BUILD_VERSION%
artifacts:
- path: distribute\*.7z
  name: 7z
deploy: off