//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Dn-FamiTracker.rc
//
#define ID_MANIFEST                     1
#define IDAPPLY                         3
#define IDC_IMPORT                      4
#define IDC_EDIT                        5
#define IDC_SAVE                        6
#define IDC_MOVE_UP                     6
#define IDC_MOVE_DOWN                   7
#define IDD_ABOUTBOX                    100
#define IDS_CLEARPATTERN                101
#define IDS_CLIPBOARD_COPY_ERROR        102
#define IDD_CONFIG_EMULATION            102
#define IDS_CLIPBOARD_PASTE_ERROR       103
#define IDS_DPCM_SPACE_FORMAT           104
#define IDS_ABOUT_TOOLTIP_WEB2          105
#define IDS_INSTRUMENT_EDITOR_TITLE     106
#define IDS_INST_VERSION_UNSUPPORTED    107
#define IDS_FILE_SAVED                  108
#define IDS_MIDI_ERR_INPUT              109
#define IDS_MIDI_ERR_OUTPUT             110
#define IDS_NEW_SOUND_CONFIG            111
#define IDS_REMOVE_INSTRUMENTS          112
#define IDS_REMOVE_PATTERNS             113
#define IDS_SONG_DELETE                 114
#define IDS_SOUND_FAIL                  115
#define IDS_UNDERRUN_MESSAGE            116
#define IDS_WELCOME_VER_FORMAT          117
#define IDS_DPCM_IMPORT_INVALID_WAVEFILE 118
#define IDS_INST_FILE_ERROR             119
#define IDS_NEW_2A03_INSTRUMENT         120
#define IDS_NEW_VRC6_INSTRUMENT         121
#define IDS_NEW_VRC7_INSTRUMENT         122
#define IDS_NEW_FDS_INSTRUMENT          123
#define IDS_NEW_N163_INSTRUMENT         124
#define ID_NEXT_FRAME                   125
#define IDS_NEW_S5B_INSTRUMENT          125
#define ID_PREV_FRAME                   126
#define IDS_FRAME_DROP_COPY_NEW         126
#define IDS_FRAME_DROP_COPY             127
#define IDR_MAINFRAME                   128
#define ID_CMD_OCTAVE_NEXT              128
#define IDR_FamiTrackerTYPE             129
#define ID_CMD_OCTAVE_PREVIOUS          129
#define IDS_FRAME_DROP_MOVE             129
#define IDS_DPCM_IMPORT_QUALITY_FORMAT  130
#define IDD_MAINFRAME                   131
#define IDS_CLIPBOARD_ERROR             131
#define IDS_FILE_OPEN_ERROR             132
#define ID_CMD_NEXT_INSTRUMENT          132
#define ID_CMD_PREV_INSTRUMENT          133
#define IDS_CLEAR_RECENTS               133
#define ID_CMD_INCREASESTEPSIZE         134
#define IDS_INST_LIMIT                  135
#define ID_CMD_DECREASESTEPSIZE         135
#define IDS_CLIPBOARD_OPEN_ERROR        136
#define ID_TRACKER_TOGGLE_PLAY          136
#define IDS_CLIPBOARD_NOT_AVALIABLE     137
#define ID_TRACKER_PLAY_START           138
#define IDS_INSTRUMENT_FILE_FAIL        139
#define ID_FOCUS_FRAME_EDITOR           139
#define ID_FOCUS_PATTERN_EDITOR         140
#define IDS_CLIPPING_MESSAGE            140
#define ID_CMD_STEP_UP                  141
#define IDS_FILTER_FTI                  141
#define ID_CMD_STEP_DOWN                142
#define IDS_SAVE_FILE_ERROR             142
#define IDS_START_ERROR                 143
#define ID_CMD_INST_NUM                 143
#define ID_BLOCK_START                  144
#define IDS_INFO_TITLE                  144
#define IDD_PERFORMANCE                 145
#define ID_BLOCK_END                    145
#define IDS_INFO_AUTHOR                 145
#define IDD_SPEED                       146
#define IDS_OUT_OF_SLOTS                146
#define IDD_PCMIMPORT                   147
#define IDS_OUT_OF_SAMPLEMEM_FORMAT     147
#define IDS_DPCM_IMPORT_GAIN_FORMAT     148
#define IDS_OPEN_FILE_ERROR             149
#define IDS_INFO_COPYRIGHT              150
#define IDS_IMPORT_FAILED               151
#define IDS_IMPORT_INSTRUMENT_COUNT     153
#define IDS_IMPORT_SAMPLE_SLOTS         154
#define IDS_DPCM_IMPORT_TITLE_FORMAT    155
#define IDS_DPCM_IMPORT_WAVE_FORMAT     156
#define IDS_DPCM_IMPORT_TARGET_FORMAT   157
#define IDD_INSTRUMENT_INTERNAL         158
#define IDS_PERFORMANCE_FRAMERATE_FORMAT 158
#define IDD_INSTRUMENT_DPCM             159
#define IDS_PERFORMANCE_UNDERRUN_FORMAT 159
#define IDD_INSTRUMENT                  160
#define IDS_LOADING_FILE                160
#define IDS_FILTER_DMC                  161
#define IDS_FILTER_WAV                  162
#define IDS_FILTER_TXT                  163
#define IDS_DPCM_EDIT_INFO_FORMAT       164
#define IDS_WAVE_EXPORT_DONE            165
#define IDS_WAVE_EXPORT_FINISHED        166
#define IDS_ABOUT_TOOLTIP_MAIL          167
#define IDS_ABOUT_TOOLTIP_WEB           168
#define IDS_ABOUT_VERSION_FORMAT        169
#define IDS_PROPERTIES_CHANNELS         170
#define IDS_LOADING_DONE                171
#define IDB_KEY_BLACK                   172
#define IDS_DPCM_IMPORT_SIZE_FORMAT     172
#define IDB_KEY_BLACK_MARK              173
#define IDS_INSTRUMENT_FOLDER           173
#define IDB_KEY_WHITE                   174
#define IDS_IMPORT_GROOVE_SLOTS         174
#define IDS_REMOVE_SAMPLES              175
#define IDB_KEY_WHITE_MARK              176
#define ID_MODULE_TEST_EXPORT           176
#define IDS_SEL_REPEATED_ROW            176
#define ID_INCREASEVALUES               177
#define IDS_SEL_NONTERMINAL_SKIP        177
#define ID_DECREASEVALUES               178
#define IDS_SEL_TERMINAL_SKIP           178
#define IDI_INST_2A03                   179
#define IDS_PASTE_REPEATED_ROW          179
#define ID_INCREASEVALUESCOARSE         179
#define ID_DECREASEVALUESCOARSE         180
#define IDD_CONFIG_APPEARANCE           180
#define IDS_PASTE_NONTERMINAL           180
#define ID_CLONE_SEQUENCE               181
#define IDS_DISABLE_SAVE                181
#define ID_RECALL_CHANNEL_STATE         182
#define IDS_BOOKMARK_EMPTY              182
#define IDD_CONFIG_GENERAL              183
#define IDS_POPULATE_PATTERNS           183
#define IDS_BOOKMARK_FORMAT             184
#define IDD_PROPERTIES                  185
#define IDS_DUMP_NOT_SUPPORTED          185
#define IDS_SEQUENCE_LIMIT              186
#define IDS_FIND_NONE                   187
#define IDS_FINDRESULT_COUNT            188
#define IDS_IMPORT_SEQUENCE_COUNT       189
#define ID_FIND_NEXT                    190
#define IDS_ABOUT_TOOLTIP_BUG           191
#define IDS_TYPE_INST_NUM               192
#define IDS_INVALID_INST_NUM            193
#define IDD_CONFIG_MIDI                 194
#define IDS_EXPORT_SAMPLES_FILE         194
#define IDS_MODULE_ERROR_NONE           195
#define IDS_FIND_EDIT_DISABLED          196
#define IDS_ABOUT_TOOLTIP_WEB3          197
#define IDR_PATTERN_POPUP               198
#define IDS_ABOUT_TOOLTIP_WEB4          198
#define IDD_CONFIG_SOUND                201
#define IDS_FILE_LOAD_ERROR             204
#define IDS_CONFIG_WINDOW               205
#define IDS_SAVE_ERROR                  210
#define IDD_CONFIG_SHORTCUTS            211
#define IDD_OCTAVE                      212
#define IDI_INST_VRC6                   217
#define IDD_EXPORT                      218
#define IDI_INST_VRC7                   225
#define IDD_INSTRUMENT_VRC7             226
#define IDD_CREATEWAV                   232
#define IDD_WAVE_PROGRESS               233
#define IDD_MAINBAR                     235
#define IDR_FRAME_POPUP                 240
#define IDI_INST_N163                   245
#define IDI_INST_FDS                    246
#define IDI_INST_S5B                    247
#define IDD_INSTRUMENT_FDS              248
#define IDS_KRAID                       250
#define IDD_FRAMEBAR                    251
#define IDD_FRAMECONTROLS               251
#define IDB_TOOLBAR_256                 257
#define IDR_INSTRUMENT_POPUP            262
#define IDD_SAMPLE_EDITOR               263
#define IDD_INSTRUMENT_FDS_ENVELOPE     264
#define IDR_SAMPLES_POPUP               266
#define IDB_TOOLBAR_INST_256            277
#define IDR_SAMPLE_WND_POPUP            279
#define IDR_INSTRUMENT_TOOLBAR          280
#define IDT_INSTRUMENT                  280
#define IDD_CHANNELS                    282
#define IDD_HEADER                      283
#define IDR_PATTERN_HEADER_POPUP        285
#define IDD_COMMENTS                    288
#define IDI_INST_2A07                   289
#define IDR_FRAMEWND                    291
#define IDD_CONFIG_MIXER                292
#define IDD_INSTRUMENT_N163_WAVE        293
#define ID_TRACKER_PLAY_CURSOR          300
#define IDD_IMPORT                      301
#define IDD_DETUNE                      302
#define IDD_GROOVE                      303
#define IDR_SAMPLE_EDITOR_POPUP         304
#define IDD_FIND                        305
#define IDS_WAVE_PROGRESS_FILE_FORMAT   308
#define IDS_WAVE_PROGRESS_FRAME_FORMAT  309
#define IDS_WAVE_PROGRESS_TIME_FORMAT   310
#define IDS_WAVE_PROGRESS_ELAPSED_FORMAT 311
#define IDR_EXPORT_TEST_REPORT          311
#define IDS_SOUND_ERROR                 312
#define IDS_SOUND_BUFFER_ERROR          313
#define IDS_EDIT_MODE                   314
#define IDI_LEFT                        314
#define IDS_NORMAL_MODE                 315
#define IDS_MIDI_MESSAGE_ON_FORMAT      316
#define IDS_MIDI_MESSAGE_OFF            317
#define IDI_RIGHT                       317
#define IDS_WAVE_PROGRESS_ROW_FORMAT    318
#define IDR_SEQUENCE_POPUP              319
#define IDD_STRETCH                     323
#define IDD_BOOKMARKS                   324
#define IDD_GOTO                        326
#define IDD_SWAP                        331
#define IDD_RECORD_SETTINGS             334
#define IDD_CONFIG_VERSION              335
#define IDD_TRANSPOSE                   337
#define IDD_FINDRESULTS                 343
#define IDD_SPLIT_KEYBOARD              345
#define IDR_HTML1                       361
#define IDD_VERSION_CHECKER             369
#define IDB_ABOUT                       376
#define IDD_CONFIG_GUI                  377
#define IDC_INSTRUMENTS                 1001
#define IDC_INSTSETTINGS                1002
#define IDC_IMPORT_DETUNE               1002
#define IDC_IMPORT_GROOVE               1003
#define IDC_INSTNAME                    1005
#define IDC_SEQ_INDEX                   1007
#define IDC_ROWS                        1019
#define IDC_ROWS_SPIN                   1020
#define IDC_SPEED_SPIN                  1022
#define IDC_TEMPO_SPIN                  1023
#define IDC_FRAMES                      1026
#define IDC_FRAME_SPIN                  1027
#define IDC_KEYSTEP                     1028
#define IDC_KEYSTEP_SPIN                1029
#define IDC_TEMPO                       1030
#define IDC_FRAME_DEC                   1035
#define IDC_FRAME_INC                   1036
#define IDC_KEYREPEAT                   1038
#define IDC_SAMPLE_RATE                 1039
#define IDC_RESAMPLING                  1040
#define IDC_BUF_LENGTH                  1041
#define IDC_SAMPLESIZE                  1041
#define IDC_BASS_FREQ                   1042
#define IDC_CHANGE_ALL                  1043
#define IDC_TREBLE_DAMP                 1043
#define IDC_BUF_LEN                     1044
#define IDC_BASS_FREQ_T                 1045
#define IDC_NAME                        1046
#define IDC_TREBLE_DAMP_T               1046
#define IDC_ARTIST                      1047
#define IDC_TREBLE_FREQ                 1047
#define IDC_COPYRIGHT                   1048
#define IDC_TREBLE_FREQ_T               1048
#define IDC_VOLUME_T                    1050
#define IDC_SPEED_SLD                   1051
#define IDC_SPEED                       1052
#define IDC_QUALITY                     1053
#define IDC_VOLUME                      1054
#define IDC_QUALITY_FRM                 1056
#define IDC_VOLUME_FRM                  1057
#define IDC_CPU                         1058
#define IDC_CPU_BAR                     1059
#define IDC_FRAMERATE                   1060
#define IDC_UNDERRUN                    1061
#define IDC_DEVICES                     1063
#define IDC_MASTER_SYNC                 1065
#define IDC_KEY_RELEASE                 1066
#define IDC_CHANMAP                     1067
#define IDC_SONG_NAME                   1067
#define IDC_SONG_ARTIST                 1068
#define IDC_MML                         1068
#define IDC_VELOCITY                    1068
#define IDC_SONG_COPYRIGHT              1069
#define IDC_ARPEGGIATE                  1069
#define IDC_FONT                        1071
#define IDC_PATTERNCOLORS               1072
#define IDC_ABOUT1                      1072
#define IDC_ABOUT2                      1073
#define IDC_DISPLAYFLATS                1073
#define IDC_SHORTCUTS                   1074
#define IDC_OCTAVE                      1075
#define IDC_SAMPLES                     1076
#define IDC_INST_TAB                    1077
#define IDC_TABLE                       1078
#define IDC_PITCH                       1079
#define IDC_LOAD                        1080
#define IDC_ZOOM                        1080
#define IDC_UNLOAD                      1081
#define IDC_SAMPLE_LIST                 1082
#define IDC_SPACE                       1083
#define IDC_KEYBOARD                    1084
#define IDC_FREE_SEQ                    1086
#define IDC_COL_ITEM                    1100
#define IDC_PICK_COL                    1101
#define IDC_COL_PREVIEW                 1102
#define IDC_BUTTON_APPEARANCE_SAVE      1103
#define IDC_SCHEME                      1104
#define IDC_PREVIEW                     1105
#define IDC_BUTTON_APPEARANCE_LOAD      1106
#define IDC_PAL                         1112
#define IDC_LOOP                        1118
#define IDC_OUTDEVICES                  1124
#define IDC_INDEVICES                   1126
#define IDC_SUBTUNE                     1127
#define IDC_PAGELENGTH                  1129
#define IDC_DEFAULT                     1132
#define IDC_EXPANSION                   1135
#define IDC_VIBRATO                     1136
#define IDC_CLOSE                       1137
#define IDC_COMBO_LINEARPITCH           1137
#define IDC_EXPORT                      1142
#define IDC_OUTPUT                      1143
#define IDC_ADD                         1146
#define IDC_SONG_ADD                    1146
#define IDC_REMOVE                      1147
#define IDC_SONG_REMOVE                 1147
#define IDC_FOLLOW                      1147
#define IDC_PATCH                       1148
#define IDC_SONG_DOWN                   1148
#define IDC_TYPE                        1149
#define IDC_SONG_UP                     1149
#define IDC_SONGLIST                    1150
#define IDC_SONGNAME                    1151
#define IDC_SONG_IMPORT                 1152
#define IDC_HIGHLIGHT1                  1153
#define IDC_SONG_INSERT                 1153
#define IDC_PROGRESS_BAR                1154
#define IDC_HIGHLIGHT2                  1154
#define IDC_TIMES                       1155
#define IDC_KEY_NOTE_RELEASE            1155
#define IDC_SECONDS                     1156
#define IDC_KEY_CLEAR                   1156
#define IDC_KEY_REPEAT                  1157
#define IDC_BEGIN                       1159
#define IDC_CANCEL                      1160
#define IDC_KEY_ECHO_BUFFER             1161
#define IDC_RADIO_LOOP                  1162
#define IDC_RADIO_TIME                  1163
#define IDC_FOLLOW_TOGGLE               1164
#define IDC_SPIN_LOOP                   1165
#define IDC_PROGRESS_LBL                1166
#define IDC_SPIN_TIME                   1166
#define IDC_PROGRESS_FILE               1167
#define IDC_HIGHLIGHTSPIN1              1167
#define IDC_TIME                        1168
#define IDC_KEY_NOTE_CUT                1168
#define IDC_HIGHLIGHTSPIN2              1168
#define IDC_SEQUENCE_SPIN               1171
#define IDC_SEQUENCE_STRING             1172
#define IDC_SAMPLE                      1175
#define IDC_M_AM                        1177
#define IDC_M_VIB                       1178
#define IDC_M_EG                        1179
#define IDC_M_KSR2                      1180
#define IDC_M_MUL                       1181
#define IDC_M_KSL                       1182
#define IDC_TL                          1184
#define IDC_M_DM                        1185
#define IDC_PRESET_SINE                 1185
#define IDC_M_AR                        1186
#define IDC_PRESET_TRIANGLE             1186
#define IDC_M_DR                        1187
#define IDC_PRESET_PULSE_50             1187
#define IDC_PRESET_SAWTOOTH             1188
#define IDC_M_SL                        1188
#define IDC_M_RR                        1189
#define IDC_MOD_PRESET_FLAT             1189
#define IDC_C_AM                        1190
#define IDC_MOD_PRESET_SINE             1190
#define IDC_C_VIB                       1191
#define IDC_MOD_RATE                    1191
#define IDC_C_EG                        1192
#define IDC_MOD_RATE_SPIN               1192
#define IDC_C_KSR                       1193
#define IDC_MOD_DEPTH                   1193
#define IDC_LOOP_POINT                  1193
#define IDC_C_MUL                       1194
#define IDC_MOD_DEPTH_SPIN              1194
#define IDC_C_KSL                       1195
#define IDC_MOD_DELAY                   1195
#define IDC_PLAY                        1195
#define IDC_MOD_DELAY_SPIN              1196
#define IDC_DELETE                      1197
#define IDC_PRESET_PULSE_25             1197
#define IDC_C_DM                        1197
#define IDC_C_AR                        1198
#define IDC_C_DR                        1199
#define IDC_C_SL                        1200
#define IDC_TILT                        1200
#define IDC_C_RR                        1201
#define IDC_STATIC_PITCH                1201
#define IDC_DELTASTART                  1202
#define IDC_FB                          1202
#define IDC_MAIL                        1208
#define IDC_WEBPAGE                     1209
#define IDC_BUG                         1210
#define IDC_WEBPAGE2                    1211
#define IDC_WEBPAGE3                    1213
#define IDC_WEBPAGE4                    1214
#define IDC_ADDED_LIST                  1217
#define IDC_FONT_SIZE                   1219
#define IDC_COPY_WAVE                   1220
#define IDC_PASTE_WAVE                  1221
#define IDC_COPY_TABLE                  1222
#define IDC_AVAILABLE_TREE              1222
#define IDC_PASTE_TABLE                 1223
#define IDC_COPY                        1225
#define IDC_PASTE                       1226
#define IDC_WAVE_SIZE                   1227
#define IDC_WAVE_POS                    1228
#define IDC_N163_DELETE                 1229
#define IDC_KEY                         1230
#define IDC_CLEAR                       1231
#define IDC_COMMENTS                    1232
#define IDC_CHECK_COMPACT               1233
#define IDC_CHECK_SWAP_ALL              1233
#define IDC_CHECK_RECORDER_RESET        1233
#define IDC_CHECK_VERSION_LOAD          1233
#define IDC_CHECK_BOOKMARK_HIGH1        1234
#define IDC_NTSC                        1234
#define IDC_CHECK_TRSP_ALL              1234
#define IDC_CHECK_BOOKMARK_HIGH2        1235
#define IDC_DUAL                        1236
#define IDC_N163_ADD                    1237
#define IDC_LEVEL_VRC6                  1239
#define IDC_LEVEL_VRC7                  1240
#define IDC_LEVEL_MMC5                  1241
#define IDC_LEVEL_FDS                   1242
#define IDC_SHOWONOPEN                  1247
#define IDC_CHANNELS                    1250
#define IDC_CHANNELS_NR                 1251
#define IDC_COMBO_STYLE                 1255
#define IDC_COMBO_GOTO_CHIP             1255
#define IDC_COMBO_VERSION_SELECT        1255
#define IDC_TRACKS                      1257
#define IDC_ABOUT3                      1258
#define IDC_DELTA_SPIN                  1263
#define IDC_SPIN_NOTE                   1263
#define IDC_SPIN_BOOKMARK_FRAME         1263
#define IDC_SPIN_RECORDER_INTERVAL      1263
#define IDC_SPIN_TRSP_SEMITONE          1263
#define IDC_SPIN_OFFSET                 1264
#define IDC_SPIN_BOOKMARK_ROW           1264
#define IDC_DELTA_COUNTER               1265
#define IDC_SPIN_BOOKMARK_HIGH1         1265
#define IDC_BUTTON_STRETCH_EXPAND       1266
#define IDC_BUTTON_BOOKMARK_ADD         1266
#define IDC_BUTTON_TRSP_REVERSE         1266
#define IDC_BUTTON_BOOKMARK_REMOVE      1267
#define IDC_SLIDER_APU1                 1268
#define IDC_BUTTON_BOOKMARK_CLEARALL    1268
#define IDC_BUTTON_BOOKMARK_MOVEUP      1269
#define IDC_ABOUT_CONTRIB               1270
#define IDC_EDIT_CONFIG_DESC            1270
#define IDC_EDIT_STRETCH_MAP            1270
#define IDC_BUTTON_BOOKMARK_MOVEDOWN    1270
#define IDC_EDIT_GOTO_FRAME             1270
#define IDC_EDIT_GROOVE_FIELD           1270
#define IDC_EDIT_RECORDER_INTERVAL      1270
#define IDC_EDIT_TRSP_SEMITONE          1270
#define IDC_HEAD                        1271
#define IDC_SPIN_BOOKMARK_HIGH2         1271
#define IDC_EDIT_GOTO_ROW               1271
#define IDC_ABOUT_LIB                   1272
#define IDC_EDIT_GOTO_CHANNEL           1272
#define IDC_LEVEL_APU1                  1273
#define IDC_LEVEL_APU2                  1274
#define IDC_LEVEL_N163                  1275
#define IDC_LEVEL_S5B                   1276
#define IDC_SLIDER_APU2                 1279
#define IDC_SLIDER_VRC6                 1280
#define IDC_SLIDER_VRC7                 1281
#define IDC_SLIDER_MMC5                 1282
#define IDC_SLIDER_FDS                  1283
#define IDC_SLIDER_N163                 1284
#define IDC_SLIDER_S5B                  1285
#define IDC_EDIT_NOTE                   1295
#define IDC_EDIT_OFFSET                 1296
#define IDC_EDIT_OCTAVE                 1297
#define IDC_SLIDER_NOTE                 1298
#define IDC_SLIDER_OFFSET               1299
#define IDC_SPIN_OCTAVE                 1300
#define IDC_RADIO_NTSC                  1301
#define IDC_RADIO_PAL                   1302
#define IDC_RADIO_VRC6                  1303
#define IDC_RADIO_VRC7                  1304
#define IDC_RADIO_FDS                   1305
#define IDC_RADIO_N163                  1306
#define IDC_CHECK_ENABLE                1307
#define IDC_SLIDER_OCTAVE               1308
#define IDC_SLIDER_DETUNE_SEMITONE      1309
#define IDC_SLIDER_DETUNE_CENT          1310
#define IDC_BUTTON_RESET                1312
#define IDC_BUTTON_IMPORT               1313
#define IDC_BUTTON_EXPORT               1315
#define IDC_EXPANSION_VRC6              1331
#define IDC_EXPANSION_VRC7              1332
#define IDC_EXPANSION_FDS               1333
#define IDC_EXPANSION_MMC5              1334
#define IDC_EXPANSION_S5B               1335
#define IDC_EXPANSION_N163              1336
#define IDC_BUTTON_GROOVE               1337
#define IDC_BUTTON_FIXTEMPO             1338
#define IDC_LIST_GROOVE_TABLE           1343
#define IDC_BUTTON_GROOVEL_UP           1344
#define IDC_BUTTON_GROOVEL_DOWN         1345
#define IDC_BUTTON_GROOVEL_CLEAR        1346
#define IDC_BUTTON_GROOVEL_CLEARALL     1347
#define IDC_STATIC_GROOVE_AVERAGE       1348
#define IDC_STATIC_GROOVE_SIZE          1349
#define IDC_STATIC_GROOVE_TOTAL         1350
#define IDC_LIST_GROOVE_EDITOR          1351
#define IDC_BUTTON_GROOVE_UP            1356
#define IDC_BUTTON_GROOVE_DOWN          1357
#define IDC_EDIT_GROOVE_NUM             1358
#define IDC_EDIT_GROOVE_PAD             1359
#define IDC_BUTTON_GROOVE_COPY          1360
#define IDC_BUTTON_GROOVE_EXPAND        1362
#define IDC_BUTTON_GROOVE_SHRINK        1363
#define IDC_BUTTON_GROOVE_GENERATE      1364
#define IDC_BUTTON_GROOVE_PAD           1365
#define IDC_EDIT_GROOVE_DENOM           1366
#define IDC_SPIN_PAD                    1368
#define IDC_BUTTON_FIND_NEXT            1370
#define IDC_BUTTON_REPLACE              1371
#define IDC_CHECK_FIND_NOTE             1376
#define IDC_CHECK_FIND_VOL              1377
#define IDC_CHECK_FIND_INST             1378
#define IDC_CHECK_FIND_EFF              1379
#define IDC_EDIT_FIND_NOTE              1380
#define IDC_EDIT_FIND_VOL               1381
#define IDC_EDIT_FIND_INST              1382
#define IDC_EDIT_FIND_EFF               1383
#define IDC_EDIT_FIND_NOTE2             1384
#define IDC_EDIT_FIND_INST2             1385
#define IDC_COMBO_FIND_IN               1386
#define IDC_EDIT_FIND_VOL2              1387
#define IDC_COMBO_EFFCOLUMN             1389
#define IDC_CHECK_VERTICAL_SEARCH       1392
#define IDC_CHECK_REPLACE_NOTE          1393
#define IDC_CHECK_REPLACE_VOL           1394
#define IDC_CHECK_REPLACE_INST          1395
#define IDC_CHECK_REPLACE_EFF           1396
#define IDC_EDIT_REPLACE_NOTE           1397
#define IDC_EDIT_REPLACE_VOL            1398
#define IDC_EDIT_REPLACE_INST           1399
#define IDC_EDIT_REPLACE_EFF            1400
#define IDC_CHECK_FIND_REMOVE           1401
#define IDC_DETUNE_INFO_NTSC            1402
#define IDC_CHECK_FIND_NEGATE           1402
#define IDC_DETUNE_INFO_PAL             1403
#define IDC_DETUNE_INFO_SAW             1404
#define IDC_DETUNE_INFO_VRC7            1405
#define IDC_DETUNE_INFO_FDS             1406
#define IDC_DETUNE_INFO_N163            1407
#define IDC_CONFIG_LIST                 1410
#define IDC_BUTTON_STRETCH_SHRINK       1411
#define IDC_STRETCH_TEST                1412
#define IDC_BUTTON_STRETCH_RESET        1413
#define IDC_BUTTON_STRETCH_INVERT       1414
#define IDC_LIST_BOOKMARKS              1415
#define IDC_BUTTON_BOOKMARK_UPDATE      1416
#define IDC_EDIT_BOOKMARK_FRAME         1417
#define IDC_EDIT_BOOKMARK_ROW           1418
#define IDC_EDIT_BOOKMARK_NAME          1420
#define IDC_EDIT_BOOKMARK_HIGH1         1421
#define IDC_EDIT_BOOKMARK_HIGH2         1422
#define IDC_CHECK_BOOKMARK_PERSIST      1424
#define IDC_BUTTON_BOOKMARK_SORTP       1425
#define IDC_BUTTON_BOOKMARK_SORTN       1426
#define IDC_N163_WAVES                  1427
#define IDC_COMBO_SWAP_CHIP1            1428
#define IDC_COMBO_SWAP_CHIP2            1429
#define IDC_EDIT_SWAP_CHAN1             1430
#define IDC_EDIT_SWAP_CHAN2             1431
#define IDC_EDIT_RECORDER_COUNT         1431
#define IDC_SPIN_RECORDER_COUNT         1432
#define IDC_CHECK_VERSION_EDIT          1433
#define IDC_CHECK_VERSION_SAVE          1434
#define IDC_RADIO_SEMITONE_INC          1436
#define IDC_RADIO_SEMITONE_DEC          1437
#define IDC_BUTTON_TRSP_CLEAR           1438
#define IDC_SLIDER_VERSION_ERRORLEVEL   1439
#define IDC_STATIC_VERSION_ERROR        1440
#define IDC_BUTTON_FIND_REPLACEALL      1441
#define IDC_BUTTON_FIND_PREVIOUS        1442
#define IDC_LIST_FINDRESULTS            1443
#define IDC_STATIC_FINDRESULT_COUNT     1445
#define IDC_BUTTON_REPLACE_PREVIOUS     1446
#define IDC_BUTTON_FIND_ALL             1447
#define IDC_COMBO_SPLIT_NOTE            1448
#define IDC_COMBO_SPLIT_OCTAVE          1449
#define IDC_COMBO_SPLIT_INST            1451
#define IDC_COMBO_SPLIT_TRSP            1452
#define IDC_CHECK_SPLIT_ENABLE          1453
#define IDC_COMBO_SPLIT_CHAN            1454
#define IDC_BUTTON_MIXER_RESET          1454
#define IDC_STATIC_DETUNE_CENT          1455
#define IDC_STATIC_DETUNE_SEMITONE      1456
#define IDC_MAINFRAME_VISUALIZER        1457
#define IDC_INST_SEQUENCE_GRAPH         1458
#define IDC_MAINFRAME_INST_TOOLBAR      1458
#define IDC_STATIC_DPCM_ZOOM            1459
#define IDC_N163_OFFSET_SLIDER          1461
#define IDC_N163_OFFSET_EDIT            1463
#define IDC_N163_OFFSET_DB              1464
#define IDC_FONT_PERCENT                1465
#define IDC_BIT_REVERSE                 1467
#define IDC_SEPERATE_CHANNEL_EXPORT     1469
#define IDC_PREVIEW_PITCH               1471
#define IDC_IDLE_REFRESH                1475
#define IDC_IDLE_REFRESH_T              1476
#define IDC_MAXCHANVIEW_T               1477
#define IDC_COMBO1                      1478
#define IDC_COMBO_FDS_EMULATOR          1478
#define IDC_CHECK1                      1482
#define IDC_N163_MULTIPLEXER            1482
#define IDC_UPDATE_REMIND               1482
#define IDC_PRECISEREGPITCH_CHECK         1482
#define IDC_SLIDER_FDS_LOWPASS          1484
#define IDC_COMBO_S5B_EMULATOR          1485
#define IDC_COMBO_VRC7_PATCH            1486
#define IDC_FDS_LOWPASS_FREQ            1488
#define IDC_VERSIONDATE_MSG             1489
#define IDC_RELEASE_MSG                 1492
#define IDC_ICON_STATIC                 1493
#define IDC_PATCH_TEXT                  1495
#define IDC_MAXCHANVIEW                 1496
#define IDC_MAXCHANVIEW_SLIDER          1496
#define IDC_IDLE_REFRESH_SLIDER         1505
#define IDC_MAXCHANVIEW_EDIT            1508
#define IDC_IDLE_REFRESH_EDIT           1512
#define IDS_FIND_BEGIN                  9001
#define IDS_FIND_END                    9002
#define ID_TRACKER_PLAY                 32771
#define ID_TRACKER_PLAYPATTERN          32775
#define ID_TRACKER_STOP                 32776
#define ID_TRACKER_EDIT                 32777
#define ID_TRACKER_KILLSOUND            32778
#define ID_FILE_CREATE_NSF              32807
#define ID_EDIT_DELETE                  32820
#define ID_TRACKER_NTSC                 32824
#define ID_TRACKER_PAL                  32825
#define ID_SPEED_CUSTOM                 32828
#define ID_HELP_PERFORMANCE             32829
#define ID_EDIT_PASTEOVERWRITE          32831
#define ID_TRANSPOSE_INCREASENOTE       32833
#define ID_TRANSPOSE_DECREASENOTE       32834
#define ID_TRANSPOSE_INCREASEOCTAVE     32835
#define ID_TRANSPOSE_DECREASEOCTAVE     32836
#define ID_EDIT_SELECTALL               32847
#define ID_FILE_GENERALSETTINGS         32851
#define ID_EDIT_ENABLEMIDI              32853
#define ID_TRACKER_PLAYROW              32858
#define ID_SPEED_DEFAULT                32893
#define ID_MODULE_MODULEPROPERTIES      32895
#define ID_EDIT_PASTEMIX                32899
#define ID_MODULE_MOVEFRAMEDOWN         32902
#define ID_MODULE_MOVEFRAMEUP           32903
#define ID_MODULE_SAVEINSTRUMENT        32909
#define ID_MODULE_LOADINSTRUMENT        32911
#define ID_MODULE_ADDINSTRUMENT         32915
#define ID_MODULE_REMOVEINSTRUMENT      32916
#define ID_TRACKER_SOLOCHANNEL          32940
#define ID_TRACKER_TOGGLECHANNEL        32941
#define ID_MODULE_EDITINSTRUMENT        32943
#define ID_NEXT_SONG                    32944
#define ID_PREV_SONG                    32945
#define ID_EDIT_INSTRUMENTMASK          32948
#define ID_TRACKER_SWITCHTOTRACKINSTRUMENT 32949
#define ID_FILE_CREATEWAV               32954
#define ID_VIEW_CONTROLPANEL            32956
#define ID_EDIT_CLEARPATTERNS           32958
#define ID_EDIT_INTERPOLATE             32959
#define ID_POPUP_SOLOCHANNEL            32962
#define ID_POPUP_TOGGLECHANNEL          32963
#define ID_MODULE_DUPLICATEFRAME        32964
#define ID_EDIT_REVERSE                 32984
#define ID_INSTRUMENT_REMOVE            32996
#define ID_INSTRUMENT_EDIT              32997
#define ID_INSTRUMENT_CLONE             32998
#define ID_FRAME_COPY                   33000
#define ID_FRAME_PASTE                  33001
#define ID_EDIT_REPLACEINSTRUMENT       33002
#define ID_CLEANUP_REMOVEUNUSEDPATTERNS 33016
#define ID_HELP_EFFECTTABLE             33017
#define ID_CLEANUP_REMOVEUNUSEDINSTRUMENTS 33022
#define ID_POPUP_SPECTRUMANALYZER       33027
#define ID_POPUP_NOTHING                33028
#define ID_POPUP_PICKUPROW              33032
#define ID_POPUP_UNMUTEALLCHANNELS      33037
#define ID_MODULE_CHANNELS              33038
#define ID_MODULE_REMOVEFRAME           33050
#define ID_MODULE_COMMENTS              33051
#define ID_MODULE_INSERTFRAME           33052
#define ID_INSTRUMENT_NEW               33053
#define ID_INSTRUMENT_LOAD              33054
#define ID_INSTRUMENT_SAVE              33055
#define ID_DECAY_SLOW                   33066
#define ID_DECAY_FAST                   33067
#define ID_INSTRUMENT_DEEPCLONE         33070
#define ID_EDIT_FIND_TOGGLE             33071
#define ID_MODULE_DUPLICATEFRAMEPATTERNS 33074
#define ID_EDIT_EXPANDPATTERNS          33075
#define ID_EDIT_SHRINKPATTERNS          33076
#define ID_FRAMEEDITOR_TOP              33081
#define ID_FRAMEEDITOR_LEFT             33082
#define ID_TOGGLE_SPEED                 33092
#define ID_FRAME_CUT                    33099
#define ID_FRAME_DELETE                 33101
#define ID_FILE_IMPORTTEXT              33104
#define ID_FILE_EXPORTTEXT              33105
#define ID_CLEANUP_MERGEDUPLICATEDPATTERNS 33106
#define ID_POPUP_SAMPLESCOPE2           33107
#define ID_POPUP_SAMPLESCOPE1           33108
#define ID_EDIT_VOLUMEMASK              33111
#define ID_FRAME_PASTENEWPATTERNS       33116
#define ID_HELP_FAQ                     33122
#define ID_TRACKER_DISPLAYREGISTERSTATE 33126
#define ID_KRAID1                       33130
#define ID_KRAID2                       33131
#define ID_KRAID3                       33132
#define ID_KRAID4                       33133
#define ID_KRAID5                       33134
#define ID_TOGGLE_MULTIPLEXER           33135
#define ID_MODULE_DETUNE                33136
#define ID_MODULE_GROOVE                33137
#define ID_FILE_EXPORTROWS              33141
#define ID_MODULE_DUPLICATECURRENTPATTERN 33142
#define ID_CLEANUP_REMOVEUNUSEDDPCMSAMPLES 33143
#define ID_EDIT_PASTEINSERT             33145
#define ID_PASTESPECIAL_CURSOR          33146
#define ID_PASTESPECIAL_SELECTION       33147
#define ID_PASTESPECIAL_FILL            33148
#define ID_CLEANUP_POPULATEUNIQUEPATTERNS 33150
#define ID_EDIT_STRETCHPATTERNS         33153
#define IDC_COMPACT_TOGGLE              33155
#define ID_SELECT_NONE                  33157
#define ID_SELECT_ROW                   33159
#define ID_SELECT_PATTERN               33160
#define ID_SELECT_FRAME                 33161
#define ID_SELECT_CHANNEL               33162
#define ID_SELECT_TRACK                 33163
#define ID_SELECT_COLUMN                33164
#define ID_COPYAS_TEXT                  33165
#define ID_COPYAS_VOLUMESEQUENCE        33166
#define ID_COPYAS_PPMCK                 33167
#define ID_EDIT_GOTO                    33168
#define ID_MODULE_BOOKMARK              33170
#define ID_BOOKMARKS_TOGGLE             33171
#define ID_BOOKMARKS_PREVIOUS           33173
#define ID_BOOKMARKS_NEXT               33174
#define ID_MODULE_ESTIMATESONGLENGTH    33175
#define ID_EDIT_SWAPCHANNELS            33177
#define ID_TRACKER_RECORDTOINST         33178
#define ID_TRACKER_RECORDERSETTINGS     33179
#define ID_POPUP_SPECTRUMANALYZER2      33182
#define ID_TRANSPOSE_CUSTOM             33183
#define ID_TRACKER_TOGGLECHIP           33184
#define ID_TRACKER_SOLOCHIP             33185
#define ID_MODULE_LINEARPITCH           33189
#define ID_RECENTFILES_CLEAR            33190
#define ID_FIND_PREVIOUS                33192
#define ID_EDIT_SPLITKEYBOARD           33193
#define ID_VIEW_AVERAGEBPM              33194
#define ID_TRACKER_PLAY_MARKER          33196
#define ID_TRACKER_SET_MARKER           33197
#define ID_FRAME_PASTEOVERWRITE         33198
#define ID_SELECT_OTHER                 33199
#define ID_HELP_VERSION_CHECK           33204
#define ID_VIEW_CONTROLPANELPOSITION    33205
#define ID_CONTROLPANELPOSITION_TOP     33206
#define ID_CONTROLPANELPOSITION_LEFT    33207
#define ID_CONTROLPANELPOSITION_RIGHT   33208
#define ID_FRAMEEDITORPOSITION_POPUP    33209
#define ID_CONTROLPANELPOSITION_POPUP   33210
#define ID_CONTROLPANEL_TOP             33211
#define ID_CONTROLPANEL_LEFT            33212
#define ID_CONTROLPANEL_RIGHT           33213
#define ID_CONTROLPANEL_POPUP           33214
#define ID_INSTRUMENT_ADD_2A03          36864
#define ID_INSTRUMENT_ADD_FDS           36865
#define ID_INSTRUMENT_ADD_MMC5          36866
#define ID_INSTRUMENT_ADD_N163          36867
#define ID_INSTRUMENT_ADD_S5B           36868
#define ID_INSTRUMENT_ADD_VRC6          36869
#define ID_INSTRUMENT_ADD_VRC7          36870
#define ID_INDICATOR_CHIP               53248
#define ID_INDICATOR_INSTRUMENT         53249
#define ID_INDICATOR_OCTAVE             53250
#define ID_INDICATOR_RATE               53251
#define ID_INDICATOR_TEMPO              53252
#define ID_INDICATOR_TIME               53253
#define ID_INDICATOR_POS                53254
#define ID_INDICATOR_DPCM_SEGMENT       53255
#define ID_INDICATOR_DPCM_SIZE          53256
#define ID_INDICATOR_DPCM_ENDPOS        53257

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        379
#define _APS_NEXT_COMMAND_VALUE         33215
#define _APS_NEXT_CONTROL_VALUE         1514
#define _APS_NEXT_SYMED_VALUE           179
#endif
#endif
