name: Dn-FamiTracker build matrix
description: Builds all given configurations and platforms/
inputs:
  configuration:
    description: "Configuration"
    required: true
  platform:
    description: "Platform"
    required: true
  cc65Binaries:
    description: "Path to output CC65 binaries. Added to PATH."
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@main
    with:
      submodules: "recursive"
      fetch-depth: 0
  - name: Setup pandoc
    uses: r-lib/actions/setup-pandoc@v2
    with:
      pandoc-version: '3.1.8'
  - name: Setup Python
    uses: actions/setup-python@main
    with:
      python-version: '3.12'
  - name: Load CC65 cache
    uses: actions/cache/restore@main
    id: cache_cc65
    with:
      path: ${{ env.cc65_path }}
      key: ${{ runner.os }}-cc65-${{ env.cc65_ref }}-${{ hashFiles('.github/actions/cache_cc65/*') }}
      fail-on-cache-miss: true
  - name: Set CC65 PATH
    run: echo "${{ inputs.cc65Binaries }}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    shell: powershell
  - name: Set msbuild PATH
    uses: microsoft/setup-msbuild@main
    with:
      msbuild-architecture: x64
  - name: Build program
    run: |
      call msbuild -m -nologo -p:Configuration="${{ inputs.configuration }}" -p:Platform="${{ inputs.platform }}"
      if %ERRORLEVEL%==1 exit %ERRORLEVEL%
    shell: cmd
