name: Dn-FamiTracker build matrix
description: Builds all given configurations and platforms/
inputs:
  configuration:
    description: "Configuration"
    required: true
  platform:
    description: "Platform"
    required: true
  commithash:
    description: "Commit SHA hash"
    required: false
    default: dev
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    with:
      submodules: "recursive"
      fetch-depth: 0
  - uses: r-lib/actions/setup-pandoc@v2
    with:
      pandoc-version: '3.1.8'
  - uses: actions/setup-python@v5
    with:
      python-version: '3.12'
  - uses: actions/cache/restore@v4
    id: cache_cc65
    with:
      path: ${{ env.cc65_path }}
      key: ${{ runner.os }}-cc65-${{ env.cc65_ref }}-${{ hashFiles('.github/actions/cache_cc65/*') }}
  - name: Set CC65 PATH
    run: echo "${{ env.cc65_path }}\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    shell: powershell
  - name: Build program
    shell: cmd
    run: |
      call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsamd64_x86.bat"
      call msbuild -m:5 -nologo -p:Configuration="${{ inputs.configuration }}" -p:Platform="${{ inputs.platform }}"
      if %ERRORLEVEL%==1 exit %ERRORLEVEL%
      call release.bat ${{ inputs.configuration }} ${{ inputs.platform }} ${{ inputs.commithash }}_${{ github.run_id }}