include_directories(.)
include_directories(Source)

add_executable(${exe}
        WIN32

        res/About.bmp
        res/Application.ico
        res/Document.ico
        res/Inst_2A03.ico
        res/Inst_2A07.ico
        res/Inst_FDS.ico
        res/Inst_N163.ico
        res/Inst_S5B.ico
        res/Inst_VRC6.ico
        res/Inst_VRC7.ico
        res/InstrumentToolbar-16.bmp
        res/InstrumentToolbar-256.bmp
        res/key_black_pressed.bmp
        res/key_black_unpressed.bmp
        res/key_white_pressed.bmp
        res/key_white_unpressed.bmp
        res/LeftArrow.ico
        res/MainToolbar-16.bmp
        res/MainToolbar-256.bmp
        res/RightArrow.ico

        Source/APU/FDS.cpp
        Source/APU/nsfplay/xgm/devices/Sound/legacy/emu2413.c
        Source/APU/nsfplay/xgm/devices/Sound/nes_apu.cpp
        Source/APU/nsfplay/xgm/devices/Sound/nes_dmc.cpp
        Source/APU/SoundChip2.cpp
        Source/APU/2A03.cpp
        Source/APU/APU.cpp
        Source/APU/Mixer.cpp
        Source/APU/MMC5.cpp
        Source/APU/N163.cpp
        Source/APU/S5B.cpp
        Source/APU/SoundChip.cpp
        Source/APU/Square.cpp
        Source/APU/VRC6.cpp
        Source/APU/VRC7.cpp
        Source/Blip_Buffer/Blip_Buffer.cpp
        Source/FFT/FftComplex.hpp
        Source/json/json.hpp
        Source/resampler/resample.cpp
        Source/resampler/resample.hpp
        Source/resampler/resample.inl
        Source/resampler/sinc.cpp
        Source/resampler/sinc.hpp
        Source/str_conv/str_conv.hpp
        Source/str_conv/utf8_conv.hpp
        Source/AboutDlg.cpp
        Source/Accelerator.cpp
        Source/Action.cpp
        Source/Bookmark.cpp
        Source/BookmarkCollection.cpp
        Source/BookmarkDlg.cpp
        Source/BookmarkManager.cpp
        Source/ChannelFactory.cpp
        Source/ChannelHandler.cpp
        Source/ChannelMap.cpp
        Source/Channels2A03.cpp
        Source/ChannelsDlg.cpp
        Source/ChannelsFDS.cpp
        Source/ChannelsMMC5.cpp
        Source/ChannelsN163.cpp
        Source/ChannelsS5B.cpp
        Source/ChannelState.cpp
        Source/ChannelsVRC6.cpp
        Source/ChannelsVRC7.cpp
        Source/Chunk.cpp
        Source/ChunkRenderBinary.cpp
        Source/ChunkRenderText.cpp
        Source/Clipboard.cpp
        Source/CommandLineExport.cpp
        Source/CommentsDlg.cpp
        Source/Compiler.cpp
        Source/CompoundAction.cpp
        Source/ConfigAppearance.cpp
        Source/ConfigEmulation.cpp
        Source/ConfigGeneral.cpp
        Source/ConfigGUI.cpp
        Source/ConfigMIDI.cpp
        Source/ConfigMixer.cpp
        Source/ConfigShortcuts.cpp
        Source/ConfigSound.cpp
        Source/ConfigVersion.cpp
        Source/ConfigWindow.cpp
        Source/ControlPanelDlg.cpp
        Source/CreateWaveDlg.cpp
        Source/CustomControls.cpp
        Source/CustomExporter.cpp
        Source/CustomExporter_C_Interface.cpp
        Source/CustomExporters.cpp
        Source/DetuneDlg.cpp
        Source/DetuneTable.cpp
        Source/DialogReBar.cpp
        Source/DirectSound.cpp
        Source/DocumentFile.cpp
        Source/DocumentWrapper.cpp
        Source/DPI.cpp
        Source/DSample.cpp
        Source/DSampleManager.cpp
        Source/Exception.cpp
        Source/ExportDialog.cpp
        Source/FamiTracker.cpp
        Source/FamiTrackerDoc.cpp
        Source/FamiTrackerTypes.cpp
        Source/FamiTrackerView.cpp
        Source/FindDlg.cpp
        Source/FrameAction.cpp
        Source/FrameEditor.cpp
        Source/FrameEditorTypes.cpp
        Source/GotoDlg.cpp
        Source/GraphEditor.cpp
        Source/Graphics.cpp
        Source/Groove.cpp
        Source/GrooveDlg.cpp
        Source/HistoryFileDlg.cpp
        Source/InstHandlerDPCM.cpp
        Source/InstHandlerVRC7.cpp
        Source/Instrument.cpp
        Source/Instrument2A03.cpp
        Source/InstrumentEditDlg.cpp
        Source/InstrumentEditorDPCM.cpp
        Source/InstrumentEditorFDS.cpp
        Source/InstrumentEditorFDSEnvelope.cpp
        Source/InstrumentEditorN163Wave.cpp
        Source/InstrumentEditorSeq.cpp
        Source/InstrumentEditorVRC7.cpp
        Source/InstrumentEditPanel.cpp
        Source/InstrumentFactory.cpp
        Source/InstrumentFDS.cpp
        Source/InstrumentFileTree.cpp
        Source/InstrumentListCtrl.cpp
        Source/InstrumentManager.cpp
        Source/InstrumentN163.cpp
        Source/InstrumentRecorder.cpp
        Source/InstrumentS5B.cpp
        Source/InstrumentVRC6.cpp
        Source/InstrumentVRC7.cpp
        Source/MainFrm.cpp
        Source/MIDI.cpp
        Source/ModSequenceEditor.cpp
        Source/ModuleException.cpp
        Source/ModuleImportDlg.cpp
        Source/ModulePropertiesDlg.cpp
        Source/NoNotifyEdit.cpp
        Source/NoteQueue.cpp
        Source/OldSequence.cpp
        Source/PatternAction.cpp
        Source/PatternCompiler.cpp
        Source/PatternComponent.cpp
        Source/PatternData.cpp
        Source/PatternEditor.cpp
        Source/PatternEditorTypes.cpp
        Source/PatternNote.cpp
        Source/PCMImport.cpp
        Source/PerformanceDlg.cpp
        Source/RecordSettingsDlg.cpp
        Source/RegisterState.cpp
        Source/SampleEditorDlg.cpp
        Source/SampleEditorView.cpp
        Source/SeqInstHandler.cpp
        Source/SeqInstHandler2A03Pulse.cpp
        Source/SeqInstHandlerFDS.cpp
        Source/SeqInstHandlerN163.cpp
        Source/SeqInstHandlerS5B.cpp
        Source/SeqInstHandlerSawtooth.cpp
        Source/SeqInstrument.cpp
        Source/Sequence.cpp
        Source/SequenceCollection.cpp
        Source/SequenceEditor.cpp
        Source/SequenceManager.cpp
        Source/SequenceParser.cpp
        Source/SequenceSetting.cpp
        Source/Settings.cpp
        Source/SimpleFile.cpp
        Source/SizeEditor.cpp
        Source/SoundGen.cpp
        Source/SpeedDlg.cpp
        Source/SplitKeyboardDlg.cpp
        Source/stdafx.cpp
        Source/StretchDlg.cpp
        Source/SwapDlg.cpp
        Source/TextExporter.cpp
        Source/TrackerChannel.cpp
        Source/TransposeDlg.cpp
        Source/VersionChecker.cpp
        Source/VersionCheckerDlg.cpp
        Source/VisualizerBase.cpp
        Source/VisualizerScope.cpp
        Source/VisualizerSpectrum.cpp
        Source/VisualizerStatic.cpp
        Source/VisualizerWnd.cpp
        Source/WaveEditor.cpp
        Source/WaveFile.cpp
        Source/WaveformGenerator.cpp
        Source/WavegenBuiltin.cpp
        Source/WavProgressDlg.cpp

        Source/utils/ftmath.cpp


        Dn-FamiTracker.rc
        )
