name: build-artifact-publish
on:
  push:
    tags:
      - "*"
env:
  commithash: ""
  cc65_path: ${{ github.workspace }}\opt\cc65
  # Fix cc65 segfault on 64-bit LLP64 Windows builds #1694
  cc65_ref: 547d923588d870aacf0b0016c67d0f6a92a70f83
jobs:
  build-cc65:
    runs-on: windows-latest
    steps:
      # pull repo just to get the .yml files
    - uses: actions/checkout@main
      with:
        submodules: "recursive"
        fetch-depth: 0
    - uses: ./.github/actions/cache_cc65
      with:
        cc65Path: ${{ env.cc65_path }}
        cc65Ref: ${{ env.cc65_ref }}
  build-matrix-publish:
    needs: build-cc65
    runs-on: windows-2022   # we still rely on MFC/ATL v143
    strategy:
      matrix:
        platform: [x64, Win32]
        # configuration is Release only
    steps:
    - uses: actions/checkout@main
      with:
        submodules: "recursive"
        fetch-depth: 0
    - run: powershell -Command "echo "commithash=$(git describe --tags)" >> $env:GITHUB_ENV"
    - name: Build program
      uses: ./.github/actions/build_matrix
      with:
        platform: "${{ matrix.platform }}"
        configuration: "Release"
        commithash: "${{ env.commithash }}"
    - run: call release.bat Release ${{ matrix.platform }}
      shell: cmd
    - name: Upload binaries
      uses: actions/upload-artifact@main
      with:
        name: Dn-FamiTracker_${{ env.commithash }}_${{ github.run_id }}_${{ matrix.platform }}
        path: distribute/*_${{ matrix.platform }}_Release.7z
  publish-build:
    needs: build-matrix-publish
    runs-on: windows-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@main
        with:
          path: Dn-FamiTracker_artifacts
          pattern: Dn-FamiTracker_*
          merge-multiple: true
      - run: ls -R
      - name: Upload release
        uses: softprops/action-gh-release@master
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          prerelease: false
          tag_name: "${{ env.commithash }}"
          files: Dn-FamiTracker_artifacts/*.7z
