name: build-artifact
on: push
env:
  commithash: ""
  cc65_path: ${{ github.workspace }}\opt\cc65
  cc65_ref: 547d923588d870aacf0b0016c67d0f6a92a70f83
jobs:
  build-cc65:
    runs-on: windows-latest
    outputs:
      cc65Binaries: ${{ steps.cc65cache.outputs.cc65Binaries }}
    steps:
      # pull repo just to get the .yml files
    - uses: actions/checkout@main
      with:
        submodules: "recursive"
        fetch-depth: 0
    - uses: ./.github/actions/cache_cc65
      id: cc65cache
      with:
        cc65Path: ${{ env.cc65_path }}
        cc65Ref: ${{ env.cc65_ref }}
  build-matrix-artifacts:
    needs: build-cc65
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64, Win32]
        configuration: [Release, Debug, ASAN-Release, ASAN-Debug]
    steps:
      # pull repo just to get the .yml files
    - uses: actions/checkout@main
      with:
        submodules: "recursive"
        fetch-depth: 0
    - run: powershell -Command "echo "commithash=$(git describe --tags)" >> $env:GITHUB_ENV"
    - name: Build program
      uses: ./.github/actions/build_matrix
      with:
        platform: "${{ matrix.platform }}"
        configuration: "${{ matrix.configuration }}"
        cc65Binaries: ${{ needs.build-cc65.outputs.cc65Binaries }}
    - run: call release.bat ${{ matrix.configuration }} ${{ matrix.platform }} ${{ env.commithash }}_${{ github.run_id }}
      shell: cmd
    - name: Upload binaries
      uses: actions/upload-artifact@main
      with:
        name: Dn-FamiTracker_${{ env.commithash }}_${{ github.run_id }}_${{ matrix.platform }}_${{ matrix.configuration }}
        path: distribute/*_${{ matrix.platform }}_${{ matrix.configuration }}.7z
